{
 "title": "Main",
 "description": "All Supporters and Actions on one place",
 "time": { "from": "now-90d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "Engagement",
    "query": "SHOW TAG VALUES WITH KEY = \"Engagement\";"
   },
   {
    "name": "Source_Action",
    "label": "Source (Actions)",
    "query": "SHOW TAG VALUES FROM form_submissions WITH KEY = \"Source\";"
   },
   {
    "name": "Type_Action",
    "label": "Type (Action)",
    "query": "SHOW TAG VALUES FROM form_submissions WITH KEY = \"Type\";"
   },
   {
    "name": "Source_Donation",
    "label": "Source (Donation)",
    "query": "SHOW TAG VALUES FROM Donations  WITH KEY = \"Source\";"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Supporters",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Supporters",
     "select": [
      [
       { "params": [ "Supporters" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "Engagement", "operator": "=~", "value": "/^$Engagement$/" }
     ]
    }
   ]
  },
  {
   "title": "Opt-In",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Supporters",
     "select": [
      [
       { "params": [ "OptIn" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Engagement", "operator": "=~", "value": "/^$Engagement$/" }
     ]
    }
   ]
  },
  {
   "title": "Supporters",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_Engagement",
     "groupBy": [
      { "params": [ "Engagement" ], "type": "tag" }
     ],
     "measurement": "Supporters",
     "select": [
      [
       { "params": [ "Supporters" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Engagement", "operator": "=~", "value": "/^$Engagement$/" }
     ]
    }
   ]
  },
  {
   "title": "Supporters by time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Supporters",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Supporters",
     "select": [
      [
       { "params": [ "Supporters" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "Engagement", "operator": "=~", "value": "/^$Engagement$/" }
     ]
    }
   ]
  },
  { "title": "Supporters (absolute)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "$Engagement",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 8 },
   "repeat": "Engagement",
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Supporters",
     "select": [
      [
       { "params": [ "Supporters" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "Engagement", "operator": "=~", "value": "/^$Engagement$/" }
     ]
    }
   ]
  },
  { "title": "Supporters in %", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "$Engagement in %",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 11 },
   "repeat": "Engagement",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Supporters",
     "select": [
      [
       { "params": [ "Supporters_p" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Engagement", "operator": "=~", "value": "/^$Engagement$/" }
     ]
    }
   ]
  },
  { "title": "Actions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Actions",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "alias": "$tag_Action $tag_Type",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "Action" ], "type": "tag" },
      { "params": [ "Type" ], "type": "tag" }
     ],
     "measurement": "form_submissions",
     "select": [
      [
       { "params": [ "Actions taken" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Actions taken" ], "type": "alias" }
      ],
      [
       { "params": [ "New" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "New" ], "type": "alias" }
      ],
      [
       { "params": [ "OptInRate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Optin" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Source", "operator": "=~", "value": "/^$Source_Action$/" },
      { "condition": "AND", "key": "Type", "operator": "=~", "value": "/^$Type_Action$/" }
     ]
    }
   ]
  },
  {
   "title": "Donations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true
  },
  {
   "title": "Donations",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "Donation" ], "type": "tag" },
      { "params": [ "Source" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Donations",
     "select": [
      [
       { "params": [ "Donations taken" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Donations taken" ], "type": "alias" }
      ],
      [
       { "params": [ "Donations in €" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Donations in €" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Source", "operator": "=~", "value": "/^$Source_Donation$/" }
     ]
    }
   ]
  }
 ]
}